// Generated by scripts/vendor-abi.ts — do not edit by hand.
// {"name":"LaunchTokenDeployer","contractName":"LaunchTokenDeployer","chainId":5042,"address":"0xFf70918Ef17A2D74d683a8297813B177BaFaD1f4","compilerVersion":"0.8.26+commit.8a97fa7a.Emscripten.clang","verifiedAt":"2026-09-12T03:52:29.154Z","sources":{"sourcify":null,"explorer":"https://arcexplorer.org/address/0xFf70918Ef17A2D74d683a8297813B177BaFaD1f4","note":"Not on Sourcify; explorer ABI cross-checked against the robinhood contract of the same role."}}
export const arcLaunchTokenDeployerAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "factoryInitializerAddress",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "name": "AlreadyInitialized",
    "type": "error",
    "inputs": []
  },
  {
    "name": "InvalidConfig",
    "type": "error",
    "inputs": []
  },
  {
    "name": "TokenAlreadyExists",
    "type": "error",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "name": "Unauthorized",
    "type": "error",
    "inputs": []
  },
  {
    "name": "deploy",
    "type": "function",
    "inputs": [
      {
        "name": "scopedSalt",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "genesisParams",
        "type": "tuple",
        "components": [
          {
            "name": "factory",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "tokenName",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "tokenSymbol",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "tokenContractURI",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "metadataAuthority",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "initialRecipient",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "initialSupply",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "metadataKeys",
            "type": "string[]",
            "internalType": "string[]"
          },
          {
            "name": "metadataValues",
            "type": "string[]",
            "internalType": "string[]"
          }
        ],
        "internalType": "struct LaunchToken.GenesisParams"
      }
    ],
    "outputs": [
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "name": "factory",
    "type": "function",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "name": "factoryInitializer",
    "type": "function",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "name": "initializeFactory",
    "type": "function",
    "inputs": [
      {
        "name": "factoryAddress",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "name": "predictTokenAddress",
    "type": "function",
    "inputs": [
      {
        "name": "scopedSalt",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "genesisParams",
        "type": "tuple",
        "components": [
          {
            "name": "factory",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "tokenName",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "tokenSymbol",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "tokenContractURI",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "metadataAuthority",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "initialRecipient",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "initialSupply",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "metadataKeys",
            "type": "string[]",
            "internalType": "string[]"
          },
          {
            "name": "metadataValues",
            "type": "string[]",
            "internalType": "string[]"
          }
        ],
        "internalType": "struct LaunchToken.GenesisParams"
      }
    ],
    "outputs": [
      {
        "name": "predictedToken",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "name": "tokenBytecodeHash",
    "type": "function",
    "inputs": [
      {
        "name": "genesisParams",
        "type": "tuple",
        "components": [
          {
            "name": "factory",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "tokenName",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "tokenSymbol",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "tokenContractURI",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "metadataAuthority",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "initialRecipient",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "initialSupply",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "metadataKeys",
            "type": "string[]",
            "internalType": "string[]"
          },
          {
            "name": "metadataValues",
            "type": "string[]",
            "internalType": "string[]"
          }
        ],
        "internalType": "struct LaunchToken.GenesisParams"
      }
    ],
    "outputs": [
      {
        "name": "bytecodeHash",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "pure"
  }
] as const;
