/**
 * Turn the single root .env into one paste-ready file per deployed service.
 *
 *   pnpm env:split            → deploy/web.env, deploy/bot.env, deploy/indexer.env, deploy/db.env
 *
 * Which variable belongs to which service comes from the section headers in
 * .env.example ("# ── Privy … · bot, web ──"), so .env.example stays the
 * single source of truth. Values come from the root .env, falling back to the
 * defaults in .env.example; whatever is still empty (secrets you have not
 * pasted yet) is listed at the end so nothing is forgotten before a deploy. Paste each file into the host's raw environment editor (Railway:
 * Variables → Raw Editor; Vercel: Settings → Environment Variables → Import).
 * deploy/ is gitignored because these files hold real secrets.
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const SERVICES = ["web", "bot", "indexer", "db"] as const;
type Service = (typeof SERVICES)[number];

type Entry = { key: string; services: Service[]; comment: string[]; example: string };

/** Parse .env.example: section headers carry the services, comments travel with the next key. */
function parseExample(text: string): Entry[] {
  const entries: Entry[] = [];
  let services: Service[] = [];
  let pending: string[] = [];
  for (const raw of text.split(/\r?\n/)) {
    const line = raw.trim();
    const header = line.match(/^# ── (.+?) · ([a-z, ]+) ─+$/);
    if (header) {
      services = header[2]!.split(",").map((s) => s.trim()).filter((s): s is Service => (SERVICES as readonly string[]).includes(s));
      pending = [];
      continue;
    }
    if (line.startsWith("#")) {
      // Keep explanatory comments that sit right above a key; drop the file banner.
      if (services.length) pending.push(line);
      continue;
    }
    const kv = line.match(/^([A-Z][A-Z0-9_]*)=(.*)$/);
    if (kv) {
      entries.push({ key: kv[1]!, services, comment: pending, example: kv[2]!.trim() });
      pending = [];
    } else if (!line) pending = [];
  }
  return entries;
}

function parseEnv(text: string): Map<string, string> {
  const out = new Map<string, string>();
  for (const raw of text.split(/\r?\n/)) {
    const line = raw.trim();
    if (!line || line.startsWith("#")) continue;
    const eq = line.indexOf("=");
    if (eq < 0) continue;
    let value = line.slice(eq + 1).trim();
    if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) value = value.slice(1, -1);
    out.set(line.slice(0, eq).trim(), value);
  }
  return out;
}

/** Production defaults that differ from the local .env.example values. */
const PRODUCTION_HINT: Record<string, string> = {
  DRY_RUN: "false once the first live launch on a fresh wallet succeeded",
  SITE_URL: "https://o1bot.exchange (the public web URL, used in replies and metadata)",
  QUEUE_DRIVER: "redis on Railway when the bot and Redis run as separate services",
};

const RAILWAY_SERVICES: ReadonlySet<Service> = new Set(["bot", "indexer"]);
const isRailwayHost = (url: string) => /\.railway\.internal|\.rlwy\.net/.test(url);

/**
 * Values that must differ per host. Railway services reach Railway Postgres
 * and Redis over the private network through reference variables, which
 * Railway resolves itself; Vercel is outside that network and keeps the
 * public URL. Hosts want plain JSON logs.
 */
function productionValue(service: Service, key: string, value: string): string {
  if (key === "LOG_PRETTY") return "false";
  if (RAILWAY_SERVICES.has(service) && key === "DATABASE_URL" && isRailwayHost(value)) return "${{Postgres.DATABASE_URL}}";
  if (RAILWAY_SERVICES.has(service) && key === "REDIS_URL" && isRailwayHost(value)) return "${{Redis.REDIS_URL}}";
  return value;
}

function main() {
  const example = parseExample(readFileSync(join(root, ".env.example"), "utf8"));
  const envPath = join(root, ".env");
  const values = existsSync(envPath) ? parseEnv(readFileSync(envPath, "utf8")) : new Map<string, string>();
  if (!values.size) console.warn("no root .env found; writing templates with empty values");
  const outDir = join(root, "deploy");
  mkdirSync(outDir, { recursive: true });

  const missing: Record<Service, string[]> = { web: [], bot: [], indexer: [], db: [] };
  const warnings: string[] = [];
  for (const service of SERVICES) {
    const own = example.filter((e) => e.services.includes(service));
    const lines = [`# ${service}: paste into the host's environment editor. Generated by pnpm env:split from the root .env; never commit.`, ""];
    for (const entry of own) {
      // A value from .env wins; otherwise the non-secret default from .env.example.
      const value = productionValue(service, entry.key, values.get(entry.key) || entry.example);
      if (!value) missing[service].push(entry.key);
      for (const c of entry.comment) lines.push(c);
      if (PRODUCTION_HINT[entry.key]) lines.push(`# production: ${PRODUCTION_HINT[entry.key]}`);
      if (entry.key === "SITE_URL" && /localhost|127\.0\.0\.1/.test(value)) warnings.push(`${service}: SITE_URL still points at ${value}; set the public web URL before deploying the bot`);
      lines.push(`${entry.key}=${value}`);
    }
    const file = join(outDir, `${service}.env`);
    writeFileSync(file, lines.join("\n") + "\n");
    console.log(`${file}: ${own.length} variables${missing[service].length ? `, ${missing[service].length} still empty` : ""}`);
  }
  for (const service of SERVICES) {
    if (missing[service].length) console.log(`  ${service} empty: ${missing[service].join(", ")}`);
  }
  for (const w of warnings) console.log(`  warning: ${w}`);
}

main();
