/**
 * Vendor verified ABIs for the active o1 suite on Robinhood Chain.
 *
 * For each contract the ABI is fetched from two independent verification
 * sources (Sourcify and Robinhood Blockscout) and the script refuses to write
 * anything unless both agree. Output per contract:
 *
 *   abis/<Name>.<chainId>.<address>.json   verbatim ABI + provenance
 *   abis/<Name>.<chainId>.<address>.ts     `as const` export for viem typing
 *   abis/index.ts                          re-exports
 *
 * Run: pnpm abi:vendor   (re-run after `pnpm o1:sync` reports drift)
 */
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import o1 from "../config/o1.json" with { type: "json" };

type AbiItem = {
  type: string;
  name?: string;
  stateMutability?: string;
  inputs?: AbiParam[];
  outputs?: AbiParam[];
  anonymous?: boolean;
};
type AbiParam = { name: string; type: string; internalType?: string; indexed?: boolean; components?: AbiParam[] };

const CHAIN = o1.chains.robinhood;
const CHAIN_ID = CHAIN.chainId;
const BLOCKSCOUT = CHAIN.explorer;
const UA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0 Safari/537.36";

const CONTRACTS: Array<{ name: string; exportName: string; key: keyof typeof CHAIN.contracts }> = [
  { name: "LaunchFactory", exportName: "launchFactoryAbi", key: "factory" },
  { name: "LaunchHook", exportName: "launchHookAbi", key: "hook" },
  { name: "FeeEscrow", exportName: "feeEscrowAbi", key: "feeEscrow" },
  { name: "LaunchTokenDeployer", exportName: "launchTokenDeployerAbi", key: "launchTokenDeployer" },
];

async function fetchSourcify(address: string): Promise<{ abi: AbiItem[]; contractName: string; compilerVersion: string }> {
  const url = `https://sourcify.dev/server/v2/contract/${CHAIN_ID}/${address}?fields=abi,compilation`;
  const res = await fetch(url, { signal: AbortSignal.timeout(60_000) });
  if (!res.ok) throw new Error(`sourcify ${address}: HTTP ${res.status}`);
  const json = (await res.json()) as { abi: AbiItem[]; compilation?: { name?: string; compilerVersion?: string } };
  if (!Array.isArray(json.abi)) throw new Error(`sourcify ${address}: no abi`);
  return { abi: json.abi, contractName: json.compilation?.name ?? "", compilerVersion: json.compilation?.compilerVersion ?? "" };
}

async function fetchBlockscout(address: string): Promise<AbiItem[]> {
  const url = `${BLOCKSCOUT}/api?module=contract&action=getabi&address=${address.toLowerCase()}`;
  const res = await fetch(url, { headers: { "user-agent": UA, accept: "application/json" }, signal: AbortSignal.timeout(60_000) });
  if (!res.ok) throw new Error(`blockscout ${address}: HTTP ${res.status}`);
  const json = (await res.json()) as { status: string; result: string | null; message?: string };
  if (json.status !== "1" || !json.result) throw new Error(`blockscout ${address}: ${json.message ?? "not verified"}`);
  return JSON.parse(json.result) as AbiItem[];
}

/** Canonical form that ignores ordering and internalType noise. */
function canonical(abi: AbiItem[]): string {
  const param = (p: AbiParam): unknown => [p.name, p.type, p.indexed ?? false, (p.components ?? []).map(param)];
  const items = abi
    .map((i) => [i.type, i.name ?? "", i.stateMutability ?? "", (i.inputs ?? []).map(param), (i.outputs ?? []).map(param)])
    .map((x) => JSON.stringify(x))
    .sort();
  return JSON.stringify(items);
}

function tsFile(exportName: string, meta: Record<string, unknown>, abi: AbiItem[]): string {
  return (
    `// Generated by scripts/vendor-abi.ts — do not edit by hand.\n` +
    `// ${JSON.stringify(meta)}\n` +
    `export const ${exportName} = ${JSON.stringify(abi, null, 2)} as const;\n`
  );
}

async function main() {
  const root = path.resolve(import.meta.dirname, "..");
  const outDir = path.join(root, "abis");
  await mkdir(outDir, { recursive: true });
  const verifiedAt = new Date().toISOString();
  const indexLines: string[] = ["// Generated by scripts/vendor-abi.ts — do not edit by hand."];

  for (const c of CONTRACTS) {
    const address = CHAIN.contracts[c.key];
    if (!address) throw new Error(`config/o1.json: robinhood has no ${String(c.key)}`);
    const [sourcify, blockscout] = await Promise.all([fetchSourcify(address), fetchBlockscout(address)]);
    if (canonical(sourcify.abi) !== canonical(blockscout)) {
      throw new Error(`${c.name} ${address}: Sourcify and Blockscout ABIs differ; refusing to vendor`);
    }
    const base = `${c.name}.${CHAIN_ID}.${address}`;
    const meta = {
      name: c.name,
      contractName: sourcify.contractName,
      chainId: CHAIN_ID,
      address,
      compilerVersion: sourcify.compilerVersion,
      verifiedAt,
      sources: {
        sourcify: `https://sourcify.dev/server/v2/contract/${CHAIN_ID}/${address}`,
        blockscout: `${BLOCKSCOUT}/address/${address}?tab=contract`,
      },
    };
    await writeFile(path.join(outDir, `${base}.json`), JSON.stringify({ ...meta, abi: sourcify.abi }, null, 2) + "\n");
    await writeFile(path.join(outDir, `${base}.ts`), tsFile(c.exportName, meta, sourcify.abi));
    indexLines.push(`export { ${c.exportName} } from "./${base}";`);
    console.log(`vendored ${c.name} (${sourcify.contractName}, ${sourcify.compilerVersion}) at ${address}: ${sourcify.abi.length} items`);
  }

  await writeFile(path.join(outDir, "index.ts"), indexLines.join("\n") + "\n");
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
